# Generated by Django 5.1.1 on 2024-09-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_review_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
