# Generated by Django 5.1.1 on 2024-09-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_remove_review_user_id_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
