# Generated by Django 5.1.1 on 2024-09-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_rename_user_review_user_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user_id'), name='unique_review_per_product'),
        ),
    ]
