# Generated by Django 5.1.1 on 2024-09-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_review_unique_review_per_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
