# Generated by Django 5.1.2 on 2024-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
